### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Dxymiemiemie** [turpaultn/dcase20_task4#12]
I want to ask how much space do I need to download the dataset for your project?
Do I need to run all the scripts to download the data just for run the MT_train?

**Comment by Dxymiemiemie** [comment]
I just want to run the baseline model but I don't know how to prepare my dataset.

**Comment by Dxymiemiemie** [comment]
I just want to run the baseline model but I don't know how to prepare my dataset.

**Comment by turpaultn** [comment]
It depends, if you just want to train the SED model without the Sound separation one, you can only download the SED part.
You can check this script: [1_download_data.sh](https://github.com/turpaultn/dcase20_task4/blob/master/scripts/1_download_data.sh)

You'll have some missing files with your "real_data" and will have to send a mail to romain.serizel@loria.fr to get the other data

About the size of the dataset: 
20G	desed_soundbank (depends on the option)
23G	desed_real

**Comment by Dxymiemiemie** [comment]
thanks for your reply. One more question
Based on your your code in the 'data_generation' fold . 
In order to generate the dataset under the folder named "/dataset/audio/train/synthetic20/xxx" which is written in the main.py . Do I have to run the get_backgrouds_train in the 1_download_data.sh ?
After download about 23G real data I want to know if I can skip this process.
B

**Comment by Dxymiemiemie** [comment]
ok, I might figured it out . let me make my question clear. Can you tell me in which procedure or scripts to generate the folder '/dataset/audio/train/synthetic20/xxx' thanks!

**Comment by turpaultn** [comment]
This one : 
[generate_synth_dcase20.py](https://github.com/turpaultn/dcase20_task4/blob/master/data_generation/generate_synth_dcase20.py)
