### ISSUE TITLE
confusion matrix and per-class detection rates

### ISSUE THREAD

**Issue by Bovey0809** [turpaultn/dcase20_task4#2]
When I run the main.py, I noticed some error in the psds.py:303, `confusion matrix and per-class detection rates`
When I print the self.class_names, there isn't "WORLD" class in it.
So, should I change this line to `n_real_classes = len(self.class_names)` without minus one.
Because when minus one, some dimension error will arise on this line.`ct_rate[i, j] = counts[i, j] * self.nseconds / gt_dur[ocls]`
the "j" could be 10 and the shape of ct_rate is (9, 9), because n_real_classes is 9.

**Comment by turpaultn** [comment]
Good question, I think it is on purpose but I cannot answer it.
This question belongs to: [https://github.com/audioanalytic/psds_eval](https://github.com/audioanalytic/psds_eval)
I'm contacting @calebmarchent to take a look at it but please kindly also ask the question on their repo.
Thanks

**Comment by Bovey0809** [comment]
Thanks for replying. I read the paper for psds, and find something interesting, I also posted the issue under 'psds_eval' repo.

Here in psds.py the function `_confusion_matrix_and_rates`
shape(ct_rate) == (num_real_class, num_real_class)
len(class_names_set_no_world) = len(class_names_world_end) - 1 = num_real_class

```python
for i, cls in enumerate(class_names_set_no_world):
    for j, ocls in enumerate(cls_names_world_end):
        ct_rate[i, j] = ...
```

The j could be `len(class_names_world_end)`, and then `ct_rate[j]` will raise an index error.
Didn't you come across the error?

**Comment by tomgrainge** [comment]
Hi @Bovey0809,

Thank you for looking into the code, we're keen to have it reviewed by the community. I am looking into the issue you have raised. I will reply to you on the [issue ](https://github.com/audioanalytic/psds_eval/issues/2) raised in the psds_eval repository.

Tom

**Comment by Bovey0809** [comment]
The problem for index error is mentioned in [issue](https://github.com/audioanalytic/psds_eval/issues/2). It is because of the empty metadata file. Normally the get_duration_df(cfg.synthetic) in main.py will generate a meta file with the same file name as gt. So after deleting the empty duration file, it generates a new one, and the problem solved.
Thanks @turpaultn @tgrainge
