### ISSUE TITLE
Very high CPU usage during training (main.py)

### ISSUE THREAD

**Issue by mpariente** [turpaultn/dcase20_task4#4]
Running `main.py` with default values results in very high CPU usage up to 6400% of 64 Cpu machines. 
This looks a bit too much for the dataprep part, as the features are precomputed and augmentation is not that expensive. 

It seems to be the bottleneck for training speech as well.

**Comment by turpaultn** [comment]
After an investigation, the problem comes from the fact that none of the DataLoader do have the `num_workers`parameter set.
Since there is the CPU problem, I'm putting back all the `num_workers`.
Thanks for raising the issue !! 😄
