### ISSUE TITLE
 ModuleNotFoundError: No module named 'desed'

### ISSUE THREAD

**Issue by jabborov** [turpaultn/dcase20_task4#6]
Hello Everyone,

I am implementing Dcase20_task4 repository in Windows 10 environment. I installed all requirements except desed. When I run main.py I only received "ModuleNotFoundError: No module named 'desed'" error. I do not know how to solve this issue. Please, help me?

Environments:
Windows 10
Anaconda 3.7

**Comment by turpaultn** [comment]
Hi, 
It is because this package is not on pip or conda yet, this is the package associated with the dataset we're using: https://github.com/turpaultn/DESED

To install it, you can launch: 
`pip install desed@git+https://github.com/turpaultn/DESED`
