### ISSUE TITLE
"synthetic20_validation" not available

### ISSUE THREAD

**Issue by wangzhongyu1997** [turpaultn/dcase20_task4#7]
I can't find the dir "synthetic20_validation"

I'm trying to run ”generate_new_synthetic_data.sh“ ,but it looks for  "${SB_BASE}/audio/**_validation_**/soundbank".
there are only "synthetic/audio/**_eval_**/soundbank" and "synthetic/audio/**_train_**/soundbank"  available, and I can only generate ”synthetic20_train“ and ”synthetic20_eval“.

Would you tell me what to do?  Thank you!

**Comment by turpaultn** [comment]
Yeah, we have a new split for the papers https://hal.inria.fr/hal-02891665 & https://hal.inria.fr/hal-02891700 
I guess that's where you found the link ? 
I'm asking this question, because if you're working on the branch "papers_code" it is normal, otherwise no.

About your question, I will do a script to do the split and add the csv files of the files that needs to go in the validation set in the repo.
Would that be ok for you ?

**Comment by wangzhongyu1997** [comment]
That is OK.
I want to use the branch "papers_code" to repeat your work.
main.py and config.py requires synthetic20_validation.
Your script and csv for synthetic20_validation are wanted.
Thank you.

**Comment by turpaultn** [comment]
I have updated desed repo: https://github.com/turpaultn/DESED#21-download-soundbank 
So you can now get the validation split: 
```python
import desed
desed.download_soundbank.make_validation_sb("path/to/synthetic") # Put the path of the root of the soundbank, which is 'synthetic/' in your case.
```
This should work, and if it doesn't, please tell me.
You can now create the files with: ”generate_new_synthetic_data.sh“

If you want the jams files to have the same soundscapes, please tell me, it is on my todo list, but didn't have time to do it yet.

Also, please note that there is a problem with the reverb (alignment with the labels) made from the [sound_separation repo](https://github.com/google-research/sound-separation/blob/master/datasets/fuss/reverberate_and_mix.py). I'm telling you just in case you wanted to reproduce the results with the reverb, we should update the paper and the repo soon.

**Comment by turpaultn** [comment]
Feel free to reopen if you still have a problem
