### ISSUE TITLE
module 'desed' has no attribute 'get_backgroung_training'

### ISSUE THREAD

**Issue by Dxymiemiemie** [turpaultn/dcase20_task4#9]
module 'desed' has no attribute 'get_backgroung_training'
when i used the file 1_download_data.sh under the folder /scripts 
it reports:
File "../data_generation/get_background_training.py", line 8, in <module>
    from desed.get_backgroung_training import get_background_training
ModuleNotFoundError: No module named 'desed.get_backgroung_training'

hello, i check the package of desed but there is no model named this.
i use the way : pip install --upgrade desed@git+https://github.com/turpaultn/DESED
to install the desed.
what‘s wrong with it?
please tell me ,thanks!

**Comment by turpaultn** [comment]
Can you please use the 1.2.2 version please ? 
get_backroung_training has now been updated and we don't use the same way to choose the file anymore (it has been integrated in a class)

**Comment by Dxymiemiemie** [comment]
ok I understand it.
But dose desed ==1.2.4 can fix the problem?

**Comment by turpaultn** [comment]
No, it is when get_background_training has been deleted.
In reality, there is a small change to make because it has been replaced by " get_backgrounds_train" in download

**Comment by turpaultn** [comment]
See #10
